name: build_info

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
   
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.

    - name: Cache Coverage file
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-

    - name: Run tests
      run: sbt test

    - name: Run sonar scanning
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sbt clean coverage test
        sbt coverageAggregate
        sbt -Dsonar.login=$SONAR_TOKEN sonarScan    
