name: build_info

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:

  build:
   
    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest code
      uses: actions/checkout@v2
    
    - name: Setup Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.7

    - name: Run tests and coverage
      run: |
        sbt clean coverage test
        sbt coverageReport
        sbt coverageAggregate

    - name: Run SonarQube scanning
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt -Dsonar.login=$SONAR_TOKEN sonarScan
      # trying to fix error  
      continue-on-error: true
